<?php declare(strict_types=1);?>
<div class="admin-heading"><div><p>Operations</p><h1><?=e(ucfirst($section))?></h1></div><?php if($section==='products'):?><a class="button button--primary" href="<?=app_url('/admin/products/new')?>">Add product</a><?php endif;?></div>
<?php if(!$rows):?><div class="admin-callout"><h2>No records</h2><p>Records will appear after MySQL is configured and the workflow is used.</p></div><?php else:?><div class="admin-records"><?php foreach($rows as$row):?><article>
<?php if($section==='products'):?><div><strong><?=e($row['name'])?></strong><span><?=e($row['category_name']??'Uncategorised')?> · <?=money($row['price'])?> · Stock <?=e($row['stock'])?> · <?=!empty($row['published'])?'Published':'Hidden'?></span></div><div class="record-actions"><a class="button" href="<?=app_url('/admin/products/'.$row['id'])?>">Edit</a><form method="post" action="<?=app_url('/admin/products/'.$row['id'].'/delete')?>" data-confirm="Remove this product? Ordered products will only be unpublished."><?=csrf_field()?><button class="button">Remove</button></form></div>
<?php elseif($section==='orders'):?><div><strong><a href="<?=app_url('/admin/orders/'.$row['order_no'].'/invoice')?>"><?=e($row['order_no'])?></a></strong><span><?=e($row['name'])?> · <?=money($row['total'])?> · <?=e($row['created_at'])?></span></div><form class="record-form" method="post" action="<?=app_url('/admin/orders/'.$row['order_no'])?>"><?=csrf_field()?><select name="status"><?php foreach(['PENDING','CONFIRMED','PACKED','SHIPPED','DELIVERED','CANCELLED']as$status):?><option <?=$row['status']===$status?'selected':''?>><?=$status?></option><?php endforeach;?></select><input name="courier" value="<?=e($row['courier'])?>" placeholder="Courier"><input name="tracking_id" value="<?=e($row['tracking_id'])?>" placeholder="Tracking ID"><input name="tracking_url" value="<?=e($row['tracking_url'])?>" placeholder="Tracking URL"><input name="expected_at" value="<?=e($row['expected_at'])?>" placeholder="YYYY-MM-DD HH:MM:SS"><input name="note" placeholder="Status note"><button class="button">Update</button></form>
<?php elseif($section==='prescriptions'):?><div><strong><?=e($row['user_name'])?> — <?=e($row['original_name'])?></strong><span><?=e($row['email'])?> · <?=e($row['status'])?> · <?=e($row['created_at'])?> · <a href="<?=app_url('/api/prescriptions/file/'.$row['id'])?>" target="_blank">View secure file</a></span></div><form class="record-form" method="post" action="<?=app_url('/admin/prescriptions/'.$row['id'])?>"><?=csrf_field()?><select name="status"><?php foreach(['PENDING','APPROVED','REJECTED']as$status):?><option <?=$row['status']===$status?'selected':''?>><?=$status?></option><?php endforeach;?></select><input name="note" value="<?=e($row['review_note'])?>" placeholder="Pharmacist note"><button class="button">Record review</button></form>
<?php elseif($section==='leads'):?><div><strong><?=e($row['name']?:'Unnamed lead')?> — <?=e($row['source'])?></strong><span><?=e($row['phone'])?> <?=e($row['email'])?> · <?=e($row['message'])?></span></div><form class="record-form" method="post" action="<?=app_url('/admin/leads/'.$row['id'])?>"><?=csrf_field()?><select name="status"><?php foreach(['NEW','CONTACTED','QUALIFIED','CONVERTED','LOST']as$status):?><option <?=$row['status']===$status?'selected':''?>><?=$status?></option><?php endforeach;?></select><input name="assigned_to" value="<?=e($row['assigned_to'])?>" placeholder="Assigned to"><input name="note" value="<?=e($row['note'])?>" placeholder="Internal note"><button class="button">Save</button></form>
<?php else:?><div><strong><?=e($row['name'])?></strong><span><?=e($row['email'])?> · <?=e($row['phone'])?> · <?=e($row['order_count'])?> orders · <?=money($row['spend'])?></span></div>
<?php endif;?></article><?php endforeach;?></div><?php endif;?>
