<?php

declare(strict_types=1);

use App\Core\Database;

if(PHP_SAPI!=='cli')exit("CLI only.\n");require dirname(__DIR__).'/app/bootstrap.php';
$write=in_array('--write',$argv,true);$source=getenv('LEGACY_API')?:'https://medplus-lkr7.onrender.com';$raw=@file_get_contents(rtrim($source,'/').'/api/products?limit=2000');if(!is_string($raw))exit("Could not fetch legacy catalogue.\n");$payload=json_decode($raw,true);$items=$payload['products']??$payload;if(!is_array($items))exit("Unexpected legacy response.\n");
$forbidden=['onemg.gumlet.io','cdn01.pharmeasy.in','practostatic.com','imimg.com','netmeds.com','apollopharmacy.in','canva.link'];$slugify=static fn(string$s):string=>substr(trim((string)preg_replace('/-+/','-',preg_replace('/[^a-z0-9]+/','-',strtolower(trim($s)))),'-'),0,180);$seen=[];$categories=[];$clean=[];
foreach($items as$item){$name=trim((string)($item['name']??''));$category=trim((string)($item['category']??'Uncategorised'));if($name===''||!is_numeric($item['price']??null))continue;$slug=$slugify($name);$base=$slug;$n=2;while(isset($seen[$slug]))$slug=$base.'-'.$n++;$seen[$slug]=true;$categories[$category]=$slugify($category);$image=filter_var($item['image']??'',FILTER_VALIDATE_URL)?(string)$item['image']:null;if($image){$host=(string)parse_url($image,PHP_URL_HOST);foreach($forbidden as$blocked)if(str_contains($host,$blocked))$image=null;}$clean[]=['name'=>$name,'slug'=>$slug,'category'=>$category,'description'=>trim((string)($item['description']??'Product details available from our pharmacist.')),'price'=>(float)$item['price'],'mrp'=>isset($item['mrp'])?(float)$item['mrp']:null,'stock'=>max(0,(int)($item['stock']??0)),'brand'=>trim((string)($item['manufacturer']??''))?:null,'rx'=>!empty($item['requiresPrescription'])?1:0,'image'=>$image,'tags'=>array_slice(array_unique(array_filter(array_map(fn($v)=>strtolower(trim((string)$v)),is_array($item['tags']??null)?$item['tags']:[]))),0,25)];}
echo 'Fetched '.count($items).' rows; valid '.count($clean).'; categories '.count($categories).".\n";if(!$write){echo "Dry run only. Re-run with --write after verifying prices, stock and legal listing rules.\n";exit;}
$db=Database::connection();$db->beginTransaction();try{$categoryIds=[];$cat=$db->prepare('INSERT INTO categories(name,slug) VALUES(:name,:slug) ON DUPLICATE KEY UPDATE name=VALUES(name),id=LAST_INSERT_ID(id)');foreach($categories as$name=>$slug){$cat->execute(['name'=>$name,'slug'=>$slug]);$categoryIds[$name]=(int)$db->lastInsertId();}$product=$db->prepare('INSERT INTO products(category_id,name,slug,description,price,mrp,stock,image_url,brand,rx_required,published) VALUES(:category,:name,:slug,:description,:price,:mrp,:stock,:image,:brand,:rx,0) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),description=VALUES(description),price=VALUES(price),mrp=VALUES(mrp),stock=VALUES(stock),image_url=VALUES(image_url),brand=VALUES(brand),rx_required=VALUES(rx_required),published=0,id=LAST_INSERT_ID(id)');$clearTags=$db->prepare('DELETE FROM product_tags WHERE product_id=:id');$tag=$db->prepare('INSERT IGNORE INTO product_tags(product_id,tag) VALUES(:id,:tag)');foreach($clean as$row){$product->execute(['category'=>$categoryIds[$row['category']],'name'=>$row['name'],'slug'=>$row['slug'],'description'=>$row['description'],'price'=>$row['price'],'mrp'=>$row['mrp'],'stock'=>$row['stock'],'image'=>$row['image'],'brand'=>$row['brand'],'rx'=>$row['rx']]);$id=(int)$db->lastInsertId();$clearTags->execute(['id'=>$id]);foreach($row['tags']as$value)$tag->execute(['id'=>$id,'tag'=>$value]);}$db->commit();echo 'Imported '.count($clean)." products as UNPUBLISHED. Review real price, stock, images and Rx policy in admin, then publish.\n";}catch(Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}
