<?php

declare(strict_types=1);

namespace App\Controllers;

use App\Core\Auth;use App\Core\Csrf;use App\Core\Request;use App\Core\Response;use App\Core\View;use App\Repositories\LeadRepository;use App\Repositories\OrderRepository;use App\Repositories\PrescriptionRepository;use App\Repositories\ProductRepository;use App\Repositories\UserRepository;use PDO;

final class AdminController
{
    public function __construct(private readonly ?PDO $db,private readonly ProductRepository $products,private readonly OrderRepository $orders,private readonly PrescriptionRepository $rx,private readonly LeadRepository $leads,private readonly UserRepository $users){}
    private function guard():?Response{return Auth::isAdmin()?null:Response::redirect('/admin/login');}
    public function loginPage():Response{if(Auth::isAdmin())return Response::redirect('/admin');return Response::html(View::render('auth/login',['title'=>'Admin sign in — Genezenz','next'=>'/admin','admin'=>true]));}
    public function dashboard():Response{if($r=$this->guard())return$r;$stats=['orders'=>0,'pending_rx'=>0,'new_leads'=>0,'low_stock'=>0,'sales'=>0];if($this->db){$stats['orders']=(int)$this->db->query('SELECT COUNT(*) FROM orders')->fetchColumn();$stats['pending_rx']=(int)$this->db->query("SELECT COUNT(*) FROM prescriptions WHERE status='PENDING'")->fetchColumn();$stats['new_leads']=(int)$this->db->query("SELECT COUNT(*) FROM leads WHERE status='NEW'")->fetchColumn();$stats['low_stock']=(int)$this->db->query('SELECT COUNT(*) FROM products WHERE published=1 AND stock<=reorder_level')->fetchColumn();$stats['sales']=(float)$this->db->query("SELECT COALESCE(SUM(total),0) FROM orders WHERE status!='CANCELLED' AND created_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 30 DAY)")->fetchColumn();}return Response::html(View::render('admin/dashboard',['title'=>'Admin dashboard','stats'=>$stats],'admin'));}
    public function list(Request $request): Response
    {
        if ($response = $this->guard()) return $response;
        $section = (string)$request->params['section'];
        $titles = ['products'=>'Products','orders'=>'Orders','prescriptions'=>'Prescriptions','leads'=>'Leads','customers'=>'Customers'];
        if (!isset($titles[$section])) return Response::html(View::render('errors/404',['title'=>'Admin page not found']),404);
        $rows = match ($section) {
            'products' => $this->products->adminAll(),
            'orders' => $this->orders->all((string)($request->query['status']??'')),
            'prescriptions' => $this->rx->all(),
            'leads' => $this->leads->all(),
            'customers' => $this->users->all(),
        };
        return Response::html(View::render('admin/list',['title'=>$titles[$section].' — Admin','section'=>$section,'rows'=>$rows],'admin'));
    }
    public function productForm(Request $request):Response{if($r=$this->guard())return$r;$id=isset($request->params['id'])?(int)$request->params['id']:null;$product=$id?$this->products->adminFind($id):null;if($id&&!$product)return Response::html(View::render('errors/404',['title'=>'Product not found']),404);return Response::html(View::render('admin/product-form',['title'=>($id?'Edit':'New').' product — Admin','product'=>$product,'categories'=>$this->products->categories()],'admin'));}
    public function saveProduct(Request $request):Response{if($r=$this->guard())return$r;if(!Csrf::check((string)($request->form['_token']??'')))return$this->fail('Form expired.');$name=trim((string)($request->form['name']??''));$data=['category_id'=>(int)($request->form['category_id']??0),'name'=>$name,'slug'=>slugify((string)($request->form['slug']?:$name)),'description'=>trim((string)($request->form['description']??'')),'content'=>trim((string)($request->form['content']??'')),'price'=>max(0,(float)($request->form['price']??0)),'mrp'=>max(0,(float)($request->form['mrp']??0)),'cost_price'=>max(0,(float)($request->form['cost_price']??0)),'stock'=>max(0,(int)($request->form['stock']??0)),'reorder_level'=>max(0,(int)($request->form['reorder_level']??10)),'batch_no'=>trim((string)($request->form['batch_no']??'')),'expiry_date'=>trim((string)($request->form['expiry_date']??'')),'gst_rate'=>max(0,(float)($request->form['gst_rate']??5)),'image_url'=>trim((string)($request->form['image_url']??'')),'brand'=>trim((string)($request->form['brand']??'')),'salt_name'=>trim((string)($request->form['salt_name']??'')),'rx_required'=>isset($request->form['rx_required'])?1:0,'published'=>isset($request->form['published'])?1:0,'meta_title'=>trim((string)($request->form['meta_title']??'')),'meta_description'=>trim((string)($request->form['meta_description']??''))];if(strlen($name)<2||strlen($data['description'])<10||$data['price']<=0)return$this->fail('Name, useful description and price are required.');$newImage=null;try{$newImage=\App\Support\ProductImageStorage::store($_FILES['product_image']??[]);if($newImage)$data['image_url']=$newImage;elseif($data['image_url']!==''&&!preg_match('#^/uploads/products/[a-f0-9]{40}\\.webp$#D',$data['image_url'])&&(!filter_var($data['image_url'],FILTER_VALIDATE_URL)||strtolower((string)parse_url($data['image_url'],PHP_URL_SCHEME))!=='https'))throw new \RuntimeException('Image URL must use HTTPS.');$this->products->save($data,isset($request->params['id'])?(int)$request->params['id']:null);flash('success','Product saved.');return Response::redirect('/admin/products');}catch(\Throwable$e){\App\Support\ProductImageStorage::discard($newImage);if($e instanceof \PDOException){error_log('Product save failed: '.$e->getMessage());return$this->fail('Could not save the product. Check the slug and field values.');}return$this->fail($e->getMessage());}}
    public function removeProduct(Request$request):Response{if($r=$this->guard())return$r;if(!Csrf::check((string)($request->form['_token']??'')))return$this->fail('Form expired.');$this->products->remove((int)$request->params['id']);flash('success','Product removed or unpublished safely.');return Response::redirect('/admin/products');}
    public function updateOrder(Request$request):Response{if($r=$this->guard())return$r;if(!Csrf::check((string)($request->form['_token']??'')))return$this->fail('Form expired.');try{$this->orders->updateStatus((string)$request->params['orderNo'],(string)($request->form['status']??''),(string)Auth::user()['email'],['courier'=>trim((string)($request->form['courier']??'')),'tracking_id'=>trim((string)($request->form['tracking_id']??'')),'tracking_url'=>trim((string)($request->form['tracking_url']??'')),'expected_at'=>trim((string)($request->form['expected_at']??'')),'note'=>trim((string)($request->form['note']??''))]);flash('success','Order updated.');return Response::redirect('/admin/orders');}catch(\Throwable$e){return$this->fail($e->getMessage(),'/admin/orders');}}
    public function invoice(Request$request):Response{if($r=$this->guard())return$r;$order=$this->orders->find((string)$request->params['orderNo']);if(!$order)return Response::html('',404);return Response::html(View::render('admin/invoice',['title'=>'Invoice '.$order['order_no'],'order'=>$order],'admin'));}
    public function reviewRx(Request$request):Response{if($r=$this->guard())return$r;if(!Csrf::check((string)($request->form['_token']??'')))return$this->fail('Form expired.');$this->rx->review((int)$request->params['id'],(string)($request->form['status']??''),trim((string)($request->form['note']??'')),(string)Auth::user()['email']);flash('success','Prescription review recorded.');return Response::redirect('/admin/prescriptions');}
    public function updateLead(Request$request):Response{if($r=$this->guard())return$r;if(!Csrf::check((string)($request->form['_token']??'')))return$this->fail('Form expired.');$this->leads->update((int)$request->params['id'],(string)($request->form['status']??''),trim((string)($request->form['note']??'')),trim((string)($request->form['assigned_to']??'')));flash('success','Lead updated.');return Response::redirect('/admin/leads');}
    private function fail(string$message,string$path='/admin/products'):Response{flash('error',$message);return Response::redirect($path);}
}
